Repository empress/rfc-process-mdbook-template, pull requests merged in 2024-07, with the labels that each got.

#19 update font awesome and switch to pnpm
  .github/workflows/ci.yml
  config/ember-try.js
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: breaking

#18 feat: migrate to `ember-showdown-shiki`
  README.md
  package.json
  pnpm-lock.yaml
  tests/dummy/config/fastboot.js
  tests/dummy/text/0001-first-rfc.md
Labels: enhancement

#21 fix Lint to the Future dashboard
  .github/workflows/gh-pages.yml
Labels: internal
